plugins
{
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.21'
}
version = project.mod_version
group = project.mod_group_id
base { archivesName = project.mod_id }
java.toolchain.languageVersion = JavaLanguageVersion.of(21)
println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
sourceSets.main.resources { srcDir 'src/generated/resources' }
repositories
{
    maven { url = "https://cursemaven.com" }
    maven { url = "https://maven.blamejared.com" }
}
dependencies
{
    implementation "net.neoforged:neoforge:${neo_version}"
    compileOnly "curse.maven:bookshelf-228525:7606240"
    compileOnly "curse.maven:botany-pots-353928:7115287"
    compileOnly "curse.maven:emi-580555:6420931"
    implementation "curse.maven:balm-531761:7420963"
    implementation "curse.maven:farming-for-blockheads-261924:7652500"
    localRuntime "curse.maven:architectury-api-419699:5786327"
    localRuntime "curse.maven:bookshelf-228525:7606240"
    localRuntime "curse.maven:botany-pots-353928:7115287"
    localRuntime "curse.maven:emi-580555:6420931"
    localRuntime "curse.maven:prickle-1023259:6961457"
    localRuntime "curse.maven:tmrv-1194921:7785753"
}
runs
{
    configureEach
    {
        it.systemProperties.put('forge.logging.markers', 'REGISTRIES')
        it.systemProperties.put('forge.logging.console.level', 'debug')
    }
    client { systemProperties.put('neoforge.enabledGameTestNamespaces', project.mod_id.toString()) }
    server
    {
        systemProperties.put('neoforge.enabledGameTestNamespaces', project.mod_id.toString())
        arguments.add('--nogui')
    }
    gameTestServer { systemProperties.put('neoforge.enabledGameTestNamespaces', project.mod_id.toString()) }
    data
    {
        workingDirectory = project.file('run-data')
        arguments.addAll(['--mod', project.mod_id.toString(), '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()])
    }
}