org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.224
loader_version_range=[1,)
mod_id=fertiliserforblockheads
mod_name=Fertiliser for Blockheads
mod_license=MIT
mod_version=21.1.12+1.4.2
mod_group_id=com.goldmike.fertiliserforblockheads
mod_authors=GoldMike
mod_description=Adds missing fertilised farmland combinations to Farming for Blockheads and adds improved Botany Pots compat.