modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Trioxide-Technical-Services/Fertiliser-for-Blockheads/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="fertiliserforblockheads.png"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="farmingforblockheads"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.${mod_id}]]
modId="botanypots"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"